DATASET: 'synthia'
DATA_FORMAT: 'data'
DATA_ROOT: '/net/bvisionserver2/playpen2/mshvets/omnisynthia'
BATCH_SIZE_PER_GPU: 8
BASE_ORDER: 1
SAMPLE_ORDER: 6
FOV: 45
DIM: 32
NORMALIZATION_STATS: 'synthia'
LABEL_WEIGHT: 'synthia-none'
MODEL_TYPE: 'hexunet'
EXPERIMENT_NAME: 'transfer-learning-fov45-dim32-synthia'
LR: 0.0001
VISDOM:
  SERVER: 'bvisionserver1.cs.unc.edu'
